# Generated by Django 3.2.12 on 2022-04-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('airline_icao', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=30)),
                ('airline_code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': '航空公司',
                'verbose_name_plural': '航空公司',
                'db_table': 'Airlines',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('city', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airports_icao', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.regions')),
            ],
            options={
                'verbose_name': '机场',
                'verbose_name_plural': '机场',
                'db_table': 'Airports',
            },
        ),
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('aircrafts_rn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aircraft_type', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('airline_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.airlines')),
            ],
            options={
                'verbose_name': '飞机',
                'verbose_name_plural': '飞机',
                'db_table': 'Aircrafts',
            },
        ),
    ]
