# Generated by Django 3.2.12 on 2022-04-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_aircrafts_airlines_airports_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafts',
            name='age',
            field=models.IntegerField(default=0, verbose_name='机龄'),
        ),
        migrations.AlterField(
            model_name='aircrafts',
            name='aircraft_type',
            field=models.CharField(max_length=20, verbose_name='机型'),
        ),
        migrations.AlterField(
            model_name='aircrafts',
            name='aircrafts_rn',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='飞机注册号'),
        ),
        migrations.AlterField(
            model_name='aircrafts',
            name='airline_icao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.airlines', verbose_name='航司ICAO代码'),
        ),
        migrations.AlterField(
            model_name='aircrafts',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='载客量'),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='airline_code',
            field=models.CharField(max_length=5, verbose_name='航司代码'),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='airline_icao',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='航司ICAO代码'),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='airline_name',
            field=models.CharField(max_length=30, verbose_name='航司名'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='airports_icao',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='机场ICAO代码'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.regions', verbose_name='机场所在城市'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='name',
            field=models.CharField(max_length=30, verbose_name='机场名称'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='city',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='country',
            field=models.CharField(max_length=30, verbose_name='国家'),
        ),
    ]
