# Generated by Django 3.2.12 on 2022-04-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20220424_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
