# Generated by Django 3.2.12 on 2022-04-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20220425_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightrecords',
            name='aircrafts_rn',
        ),
        migrations.RemoveField(
            model_name='flightrecords',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='destination_icao',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='origin_icao',
        ),
        migrations.RemoveField(
            model_name='records',
            name='email',
        ),
        migrations.RemoveField(
            model_name='records',
            name='flight_records',
        ),
        migrations.DeleteModel(
            name='Aircrafts',
        ),
        migrations.DeleteModel(
            name='Airlines',
        ),
        migrations.DeleteModel(
            name='Airports',
        ),
        migrations.DeleteModel(
            name='FlightRecords',
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
