# Generated by Django 3.2.12 on 2022-04-25 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0006_auto_20220425_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('aircraft_rn', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='飞机注册号')),
                ('aircraft_type', models.CharField(max_length=20, verbose_name='机型')),
                ('age', models.IntegerField(default=0, verbose_name='机龄')),
                ('capacity', models.IntegerField(default=0, verbose_name='载客量')),
            ],
            options={
                'verbose_name': '飞机',
                'verbose_name_plural': '飞机',
                'db_table': 'Aircrafts',
            },
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('airline_iata', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='航司IATA代码')),
                ('airline_icao', models.CharField(max_length=3, verbose_name='航司ICAO代码')),
                ('airline_name', models.CharField(max_length=30, verbose_name='航司名')),
            ],
            options={
                'verbose_name': '航空公司',
                'verbose_name_plural': '航空公司',
                'db_table': 'Airlines',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_icao', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='机场ICAO代码')),
                ('name', models.CharField(max_length=30, verbose_name='机场名称')),
                ('city', models.CharField(max_length=30, verbose_name='机场所在城市')),
            ],
            options={
                'verbose_name': '机场',
                'verbose_name_plural': '机场',
                'db_table': 'Airports',
            },
        ),
        migrations.CreateModel(
            name='FlightRecords',
            fields=[
                ('flight_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='飞行记录ID')),
                ('departure_time', models.DateTimeField(verbose_name='起飞时间')),
                ('arrival_time', models.DateTimeField(verbose_name='落地时间')),
                ('delay', models.CharField(max_length=3, verbose_name='延误')),
                ('aircraft_rn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.aircrafts', verbose_name='飞机注册号')),
            ],
            options={
                'verbose_name': '飞行记录',
                'verbose_name_plural': '飞行记录',
                'db_table': 'FlightRecords',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户邮箱')),
                ('name', models.CharField(max_length=30, verbose_name='用户昵称')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('gender', models.CharField(max_length=10, verbose_name='用户性别')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.users', verbose_name='用户邮箱')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flightrecords', verbose_name='飞行记录')),
            ],
            options={
                'verbose_name': '用户飞行记录',
                'verbose_name_plural': '用户飞行记录',
                'db_table': 'Records',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='航班号')),
                ('airline_iata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.airlines', verbose_name='航司IATA代码')),
                ('destination_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_icao', to='file.airports', verbose_name='目的地机场')),
                ('origin_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_icao', to='file.airports', verbose_name='出发地机场')),
            ],
            options={
                'verbose_name': '航班',
                'verbose_name_plural': '航班',
                'db_table': 'Flight',
            },
        ),
        migrations.AddField(
            model_name='flightrecords',
            name='flight_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flights', verbose_name='航班'),
        ),
        migrations.AddField(
            model_name='aircrafts',
            name='airline_iata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.airlines', verbose_name='航司IATA代码'),
        ),
    ]
