# Generated by Django 3.2.12 on 2022-04-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircrafts',
            old_name='airline_iata',
            new_name='airline_id',
        ),
    ]
