# Generated by Django 3.2.12 on 2022-04-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_rename_airline_iata_aircrafts_airline_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircrafts',
            old_name='airline_id',
            new_name='airline_iata',
        ),
    ]
