# Generated by Django 3.2.12 on 2022-04-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flights',
            table='Flights',
        ),
    ]
