# Generated by Django 3.2.12 on 2022-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_alter_flights_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrecords',
            name='arrival_time',
            field=models.CharField(max_length=20, verbose_name='落地时间'),
        ),
        migrations.AlterField(
            model_name='flightrecords',
            name='departure_time',
            field=models.CharField(max_length=20, verbose_name='起飞时间'),
        ),
    ]
