# Generated by Django 3.2.12 on 2022-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_auto_20220426_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='用户邮箱'),
        ),
    ]
