# Generated by Django 3.2.12 on 2022-05-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0014_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightsAirplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_rn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.aircrafts', verbose_name='飞机注册号')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flightrecords', verbose_name='飞行记录')),
            ],
            options={
                'verbose_name': '航班飞机',
                'verbose_name_plural': '航班飞机',
                'db_table': 'FlightsAirplanes',
            },
        ),
        migrations.CreateModel(
            name='AirlinePossession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_rn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.aircrafts', verbose_name='飞机注册号')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flightrecords', verbose_name='飞行记录')),
            ],
            options={
                'verbose_name': '航司飞机',
                'verbose_name_plural': '航司飞机',
                'db_table': 'AirlinePossession',
            },
        ),
    ]
