# Generated by Django 3.2.12 on 2022-05-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0015_airlinepossession_flightsairplanes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airlinepossession',
            name='flight_id',
        ),
        migrations.AddField(
            model_name='airlinepossession',
            name='airline_iata',
            field=models.ForeignKey(default='BK', on_delete=django.db.models.deletion.CASCADE, to='file.airlines', verbose_name='航司IATA代码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightsairplanes',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flightrecords', verbose_name='飞行记录ID'),
        ),
        migrations.AlterField(
            model_name='records',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flightrecords', verbose_name='飞行记录ID'),
        ),
        migrations.CreateModel(
            name='To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.airports', verbose_name='机场ICAO代码')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flights', verbose_name='航班号')),
            ],
            options={
                'verbose_name': '航班终点',
                'verbose_name_plural': '航班终点',
                'db_table': 'To',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_iata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.airlines', verbose_name='航司IATA代码')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flights', verbose_name='航班号')),
            ],
            options={
                'verbose_name': '航司提供航班',
                'verbose_name_plural': '航司提供航班',
                'db_table': 'Offering',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flightrecords', verbose_name='飞行记录ID')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flights', verbose_name='航班号')),
            ],
            options={
                'verbose_name': '航班历史',
                'verbose_name_plural': '航班历史',
                'db_table': 'History',
            },
        ),
        migrations.CreateModel(
            name='From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.airports', verbose_name='机场ICAO代码')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flights', verbose_name='航班号')),
            ],
            options={
                'verbose_name': '航班起点',
                'verbose_name_plural': '航班起点',
                'db_table': 'From',
            },
        ),
    ]
