# Generated by Django 3.2.12 on 2022-05-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0016_auto_20220512_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.flightrecords', verbose_name='飞行记录'),
        ),
    ]
