# Generated by Django 3.2.12 on 2022-05-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0018_alter_records_flight_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aircrafts',
            index=models.Index(fields=['aircraft_rn'], name='Aircrafts_aircraf_f36330_idx'),
        ),
        migrations.AddIndex(
            model_name='airlines',
            index=models.Index(fields=['airline_iata'], name='Airlines_airline_e929f8_idx'),
        ),
        migrations.AddIndex(
            model_name='airports',
            index=models.Index(fields=['airport_icao'], name='Airports_airport_42cbbb_idx'),
        ),
        migrations.AddIndex(
            model_name='flightrecords',
            index=models.Index(fields=['flight_id'], name='FlightRecor_flight__734c77_idx'),
        ),
        migrations.AddIndex(
            model_name='flights',
            index=models.Index(fields=['flight_number'], name='Flights_flight__38e090_idx'),
        ),
    ]
