# Generated by Django 3.2.12 on 2022-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0019_auto_20220514_0929'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['email'], name='Users_email_838c41_idx'),
        ),
    ]
