# Generated by Django 3.2.12 on 2022-05-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0020_users_users_email_838c41_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flightrecords',
            name='FlightRecor_flight__734c77_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='Users_email_838c41_idx',
        ),
    ]
